# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5fb21f27ac803939db8ec36a6f509b9846dc8da219ae7ea0098f415ef1a2c0e0acb206255bfda1d2ec733654b55e21627ddd840eb07f27dcb0d6e1e275029c1e

test:
  secret_key_base: 70869520b22d3d2d60ba5c3c762b035a2787a11f2ae039d2892f16d6cc869d7872e48f7921dec571897337a75ff7a156f9db9517020925d195a0ec0c5b76dcea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
